spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db-migration-flyway
    username: root
    password: password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    properties:
      hibernate:
    dialact  : org.hibernate.dialect.MySQL8Dialect
  flyway:
    baseline-on-migrate: true

#spring.flyway.baseline-on-migrate=true
